export PATH="$PATH:$HOME/.local/bin"
export GEM_HOME="$(ruby -e 'puts Gem.user_dir')"
export PATH="$PATH:$GEM_HOME/bin"
export GO="/usr/local/go"
export PATH="$PATH:$GO/bin"
export GO_HOME="$HOME/go"
export PATH="$PATH:$GO_HOME/bin"
export TERMINAL="alacritty"
